subscription-matcher(1)
=======================
:doctype: manpage

NAME
----
subscription-matcher - match subscriptions to systems

SYNOPSIS
--------
*subscription-matcher* ['OPTIONS']

DESCRIPTION
-----------
subscription-matcher(1) is used to match subscriptions to systems
and generate reports. subscription-matcher(1) is able to take pre-defined
pinned matches into account when provided.

OPTIONS
-------

-h, --help::
show help message and exit

-d,--delimiter <arg>::
CSV Delimiter (Default: ,)

-o,--directory <arg>::
Output directory (Default: current directory)

-i,--input <arg>::
Input file in JSON format (Default: STDIN)

EXAMPLES:
---------

Write output files in the current directory

  $> subscription-matcher -i input.json

Print the reports to /tmp directory, incl. CSV reports

  $> subscription-matcher -i input.json -o /tmp

Use semicolon (;) as delimiter

  $> subscription-matcher -i input.json -o /tmp -d ';'

AUTHOR
------
The SUSE Manager Team

COPYING
-------
Copyright (c) 2015 SUSE LLC
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

   * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
   * Neither the name of SUSE LLC nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

