#!/bin/bash

exec java -cp $(build-classpath antlr-runtime-3 commons-io commons-lang commons-lang3 commons-math3 commons-cli commons-csv drools-compiler drools-core ecj google-gson guava kie-api kie-internal log4j mvel2 optaplanner-core slf4j/api slf4j/log4j12 xstream xmlpull xpp3 protobuf reflections subscription-matcher) -server -Xmx2G com.suse.matcher.Main "$@"
