package com.suse.matcher.rules;

import com.suse.matcher.facts.Subscription;
import com.suse.matcher.facts.CurrentTime;

rule "subscriptionNotExpired"
    when
        CurrentTime($timestamp : timestamp)
        $subscription: Subscription(expiresAt < $timestamp || startsAt > $timestamp)
    then
        retract($subscription);
end

rule "subscriptionSystemLimitHasValue"
    when
        $subscription: Subscription(quantity == null)
    then
        retract($subscription);
end
