package com.suse.marcher.inputaugmenting;

import com.suse.matcher.model.Subscription;
import com.suse.matcher.model.System;

rule "partNumber 874-005030"
    when
        $subscription : Subscription(partNumber == "874-005030")
    then
        modify($subscription) {
            cpus = 32,
            unlimitedVirtualization = true,
            stackable = false,
            usableProductIds.add((String)"1"),
            supportType = "Standard",
            lifetime = 3;
        };
end

rule "partNumber 874-005031"
    when
        $subscription : Subscription(partNumber == "874-005031")
    then
        modify($subscription) {
            cpus = 8,
            unlimitedVirtualization = true,
            stackable = false,
            usableProductIds.add((String)"1"),
            supportType = "Standard",
            lifetime = 3;
        };
end

rule "partNumber 874-005032"
    when
        $subscription : Subscription(partNumber == "874-005032")
    then
        modify($subscription) {
            cpus = 8,
            unlimitedVirtualization = true,
            stackable = false,
            usableProductIds.add((String)"1"),
            usableProductIds.add((String)"2"),
            supportType = "Standard",
            lifetime = 3;
        };
end

rule "partNumber 874-005033"
    when
        $subscription : Subscription(partNumber == "874-005033")
    then
        modify($subscription) {
            cpus = 4,
            unlimitedVirtualization = true,
            stackable = false,
            usableProductIds.add((String)"1"),
            supportType = "Standard",
            lifetime = 3;
        };
end

rule "partNumber 874-005034"
    when
        $subscription : Subscription(partNumber == "874-005034")
    then
        modify($subscription) {
            cpus = 2,
            unlimitedVirtualization = true,
            stackable = true,
            usableProductIds.add((String)"1"),
            supportType = "Standard",
            lifetime = 3;
        };
end

rule "ensure virtual systems are indeed virtual"
when
    $guest : System(physical)
    $host : System(virtualSystemIds contains $guest.id )
then
    modify($guest) {
        physical = false;
    }
end
