package com.suse.matcher.rules;

import com.suse.matcher.model.Match;
import com.suse.matcher.model.Match.Kind;
import com.suse.matcher.model.Subscription;
import com.suse.matcher.model.System;

rule "flag invalid pinned matches"
    agenda-group "OutputCollection"
    when
        $pinned_match : Match($systemId : systemId, $subscriptionId : subscriptionId, kind == Kind.USER_PINNED)
        not (Match(systemId == $systemId, subscriptionId == $subscriptionId, kind == Kind.POSSIBLE))
    then
        insert(new Match($systemId, $subscriptionId, Kind.INVALID));
end