package com.suse.matcher.rules;

import com.suse.matcher.facts.HostGuest;
import com.suse.matcher.facts.Match;
import com.suse.matcher.facts.Match.Kind;
import com.suse.matcher.facts.Subscription;
import com.suse.matcher.facts.Subscription.Policy;
import com.suse.matcher.facts.System;

rule "flag invalid pinned matches"
    agenda-group "OutputCollection"
    when
        $pinned_match : Match($systemId : systemId, $productId : productId, $subscriptionId : subscriptionId, kind == Kind.USER_PINNED)
        not (Match(systemId == $systemId, productId == $productId, subscriptionId == $subscriptionId, kind == Kind.POSSIBLE))
    then
        insert(new Match($systemId, $productId, $subscriptionId, null, Kind.INVALID));
end
