package com.suse.matcher.rules;

import com.suse.matcher.model.Subscription;
import com.suse.matcher.model.System;

// TODO: remove this rule file and replace it with real data from SCC

rule "Fake products to subscription rule for SLES"
    agenda-group "ProductIds"
    when
        $subscription : Subscription(
            partNumber == "874-005030" ||
            partNumber == "874-006260" ||
            partNumber == "874-005649" ||
            partNumber == "874-006311" ||
            partNumber == "800-TEMPORARY-X86-2CPU-STACKABLE"
        )
    then
        modify($subscription) {
            productIds.add(814L),
            productIds.add(793L),
            productIds.add(1298L),
            productIds.add(1300L),
            productIds.add(1118L);
        };
end

rule "Fake products to subscription rule for RES"
    agenda-group "ProductIds"
    when
        $subscription : Subscription(
            partNumber == "874-005649"
        )
    then
        modify($subscription) {
            productIds.add(1122L),
            productIds.add(1138L),
            productIds.add(1251L),
            red = true;
        };
end

rule "Fake products to system rule for RES"
    agenda-group "ProductIds"
    when
        $system : System(
            productIds contains 1122L ||
            productIds contains 1138L ||
            productIds contains 1251L
        )
    then
        modify($system) {
            red = true;
        };
end