package com.suse.matcher.rules;

import com.suse.matcher.facts.Subscription;
import com.suse.matcher.facts.SubscriptionProduct;
import com.suse.matcher.facts.System;
import com.suse.matcher.facts.SystemProduct;

// TODO: remove this rule file and replace it with real data from SCC

rule "Fake products to subscription rule for SLES"
    agenda-group  "FirstGroup"
    when
        $subscription : Subscription(
            partNumber == "874-005030" ||
            partNumber == "874-006260" ||
            partNumber == "874-005649" ||
            partNumber == "874-006311" ||
            partNumber == "874-006876" ||
            partNumber == "874-006875"
        )
    then
        insert(new SubscriptionProduct($subscription.id, 814L));
        insert(new SubscriptionProduct($subscription.id, 793L));
        insert(new SubscriptionProduct($subscription.id, 1298L));
        insert(new SubscriptionProduct($subscription.id, 1300L));
        insert(new SubscriptionProduct($subscription.id, 1118L));
end

rule "Fake products to subscription rule for RES"
    agenda-group  "FirstGroup"
    when
        $subscription : Subscription(
            partNumber == "874-005649"
        )
    then
        insert(new SubscriptionProduct($subscription.id, 1122L));
        insert(new SubscriptionProduct($subscription.id, 1138L));
        insert(new SubscriptionProduct($subscription.id, 1251L));

        modify($subscription) {
            red = true;
        };
end

rule "Fake products to system rule for RES"
    agenda-group  "FirstGroup"
    when
        $system : System($systemId : id)
        SystemProduct(systemId == $systemId, productId in (1122L, 1138L, 1251L))
    then
        modify($system) {
            red = true;
        };
end

rule "Fake products to subscription rule for SUSE-Cloud"
    agenda-group  "FirstGroup"
    when
        $subscription : Subscription(
            partNumber == "874-006385"
        )
    then
        insert(new SubscriptionProduct($subscription.id, 1221L));
        insert(new SubscriptionProduct($subscription.id, 1288L));
end
